[package]
name = "solana_native_programs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
bytemuck_derive = "1.8.1"
borsh = "1.5.6"
borsh-derive = "1.5.6"
solana-program = "2.2.1"